baseurl = "https://thestatsguy.netlify.app/"
languageCode = "en-us"
title = "The Stats Guy"
theme = "hugo-xmin"
googleAnalytics = "UA-165274801-1"
disqusShortname = "thestatsguy90"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "ML & Stats"
    url = "/categories/ml-stats/"
    weight = 4
[[menu.main]]
    name = "Stats finance"
    url = "/categories/stats-finance/"
    weight = 5
[[menu.main]]
    name = "Finance & Investing"
    url = "/categories/finance-investing/"
    weight = 6
[[menu.main]]
    name = "Corporate rat race"
    url = "/categories/corporate-rat-race/"
    weight = 7
[[menu.main]]
    name = "Stoicism"
    url = "/categories/stoicism/"
    weight = 8
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Explorations in topics that I enjoy the most."
    footer = "&copy; The Stats Guy 2020 | [Home](https://thestatsguy.netlify.app) | [GitHub](https://github.com/thestatsguy)"
    
# [markup.goldmark.renderer]
#     unsafe = true    