baseurl = "https://thestatsguy.netlify.app/"
languageCode = "en-us"
title = "The Stats Guy"
theme = "hugo-xmin"
googleAnalytics = "UA-165274801-1"
disqusShortname = "thestatsguy90"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 9
# [[menu.main]]
#     name = "To-read list"
#     url = "/to-read-list/"
#     weight = 10
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Explorations in topics that I enjoy the most."
    footer = "&copy; The Stats Guy 2021 | [Home](https://thestatsguy.netlify.app) | [GitHub](https://github.com/thestatsguy) | [Goodreads](https://www.goodreads.com/review/list/130206849-thestatsguy?page=1&view=covers)"
    
# [markup.goldmark.renderer]
#     unsafe = true    